name: fuel.nix
author: Oleksii Filonenko
description: Install Fuel toolchain using fuel.nix
branding:
  color: green
  icon: zap

inputs:
  components:
    description: Comma-separated list of (optionally versioned) components to install
    required: true
    default: fuel

runs:
  using: composite
  steps:
    - name: Install Nix and configure Cachix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          trusted-public-keys = fuellabs.cachix.org-1:3gOmll82VDbT7EggylzOVJ6dr0jgPVU/KMN6+Kf8qx8= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://fuellabs.cachix.org https://cache.nixos.org
    - id: parse
      run: |
        echo "components=$(for component in ${components//,/ }; do echo -n  github:FuelLabs/fuel.nix#${component//[@.]/-}\ ; done)" >> $GITHUB_OUTPUT
      env:
        components: ${{inputs.components}}
      shell: bash
    - name: nix profile install
      run: nix profile install ${{steps.parse.outputs.components}}
      shell: bash
